const coursesData = [
  {
    title: 'Artificial Intelligence & Machine Learning',
    description: 'Master python, core machine learning algorithms, deep learning models, natural language processing, and computer vision with hands-on industrial projects.',
    category: 'Data Science & AI',
    price: 4999,
    duration: '12 Weeks',
    level: 'Advanced',
    instructor: 'Dr. Alok Verma, Lead AI Architect',
    syllabus: [
      'Introduction to Python & Scientific Libraries (NumPy, Pandas, Matplotlib)',
      'Supervised Learning: Regression, Classification, Support Vector Machines, Decision Trees',
      'Unsupervised Learning: K-Means Clustering, PCA, Dimensionality Reduction',
      'Deep Learning Foundations: Artificial Neural Networks, Backpropagation',
      'Convolutional Neural Networks (CNNs) & Computer Vision applications',
      'Natural Language Processing (NLP): Text Processing, Sentiment Analysis, Transformers',
    ],
    projects: [
      'Automated Medical Image Diagnostic System',
      'Real-Time E-Commerce Customer Recommendation Engine',
      'Stock Price Forecast and Sentiment Prediction Model',
    ],
    certificationDetails: 'ISO 9001:2015 Verified Industrial Certification. Co-signed by Mountreach Solution and leading industry AI architects. Includes unique verification ID.',
    image: 'aiml',
  },
  {
    title: 'Android Development with Kotlin',
    description: 'Build native, production-ready Android applications using Kotlin, Android Jetpack, Retrofit, Room Database, and MVVM Architecture.',
    category: 'Mobile Development',
    price: 3499,
    duration: '8 Weeks',
    level: 'Intermediate',
    instructor: 'Priya Sharma, Senior Android Lead',
    syllabus: [
      'Kotlin Programming Basics, Object-Oriented Principles, and Lambdas',
      'Android Studio IDE, Activity & Fragment Lifecycle, Views and Layouts',
      'Jetpack Compose: Modern UI Toolkit, State Management, Lists & Animations',
      'Data Storage: Shared Preferences, SQLite, and Room Database',
      'REST API Integration: Networking using Retrofit & Coroutines',
      'App Publishing: Optimization, Play Store Guidelines, and Deployment',
    ],
    projects: [
      'Smart Task Manager with Local SQLite Sync',
      'Live News feed application using Retrofit & Jetpack Compose',
      'Geo-location Tracking Fitness Companion App',
    ],
    certificationDetails: 'Mountreach Certified Android Application Developer Stamp. Recognized by top mobile development agencies globally.',
    image: 'android',
  },
  {
    title: 'Full Stack Web Development',
    description: 'Comprehensive training covering frontend (HTML5, CSS3, JS), database integration, server architecture, and hosting high-performance sites.',
    category: 'Web Development',
    price: 3999,
    duration: '10 Weeks',
    level: 'Beginner',
    instructor: 'Rahul Mehta, Cloud & Web Consultant',
    syllabus: [
      'Advanced HTML5, CSS3, Flexbox, Grid, CSS Variables',
      'JavaScript ES6+, DOM manipulation, Asynchronous Operations, and Fetch API',
      'Backend basics: Express.js, HTTP methods, and Restful Routes',
      'Databases: Relational (PostgreSQL) vs Non-Relational (MongoDB)',
      'Authentication and Security (Sessions, Cookies, CORS, and Headers)',
      'Cloud Deployment: CI/CD, Git, GitHub Actions, Netlify, and Render',
    ],
    projects: [
      'Responsive Tech Consulting Corporate Website',
      'Multi-user Blogging Portal with Admin Panel',
      'Real-time Collaboration Kanban Board',
    ],
    certificationDetails: 'ISO Certified Full-Stack Developer Accreditation. Verifiable credential with lifetime validity.',
    image: 'fullstack',
  },
  {
    title: 'MERN Stack Development',
    description: 'Become a proficient JavaScript developer. Build dynamic, database-driven web applications using MongoDB, Express, React, and Node.js.',
    category: 'Web Development',
    price: 4499,
    duration: '12 Weeks',
    level: 'Intermediate',
    instructor: 'Dhananjay S., Senior Software Engineer',
    syllabus: [
      'React Essentials: Components, Props, State, Hooks (useState, useEffect)',
      'React Router & Context API: Global state and client-side page transitions',
      'Node.js & Express.js: Creating high-scale APIs, middleware, and request handling',
      'MongoDB & Mongoose: Database modeling, indexing, aggregations, and CRUD',
      'JWT Authentication & Middleware: Securing routes and student portals',
      'Full-stack Deployment: Deploying React to Vercel and Express to AWS/Render',
    ],
    projects: [
      'Feature-Rich E-learning Portal (LMS)',
      'Real-Time Chat Application with Socket.io',
      'Corporate Recruitment and Applicant Tracking System',
    ],
    certificationDetails: 'Mountreach MERN Stack Developer Verified Stamp. Co-branded with academic and industrial technology partners.',
    image: 'mern',
  },
  {
    title: 'Data Analytics & Business Intelligence',
    description: 'Learn to clean, visualize, and analyze complex datasets using SQL, Excel, Tableau, and Python Data Analysis Libraries.',
    category: 'Data Science & AI',
    price: 3799,
    duration: '8 Weeks',
    level: 'Beginner',
    instructor: 'Ananya Deshmukh, Lead BI Analyst',
    syllabus: [
      'Advanced Excel: Pivot Tables, VLOOKUP/INDEX-MATCH, and Data Modeling',
      'SQL Foundations: Querying, Joins, Aggregations, Subqueries, CTEs',
      'Data Visualisation: Building interactive dashboards using Tableau & PowerBI',
      'Python Data Exploration: Data Wrangling with Pandas & Matplotlib',
      'Statistical Analysis: Hypothesis Testing, A/B Testing, Descriptive Stats',
      'Storytelling with Data: Preparing reports for executive presentation',
    ],
    projects: [
      'Interactive Sales Performance Tableau Dashboard',
      'Retail Dataset Exploratory Data Analysis (EDA) in Python',
      'SQL-Driven Customer Churn Forecasting Report',
    ],
    certificationDetails: 'ISO 9001 Corporate Endorsed Business Analyst Certification. Includes verification seal on student profile.',
    image: 'data',
  },
  {
    title: 'Flutter Development',
    description: 'Design stunning, fast cross-platform applications for iOS and Android from a single codebase using Dart and Flutter SDK.',
    category: 'Mobile Development',
    price: 3499,
    duration: '8 Weeks',
    level: 'Intermediate',
    instructor: 'Vikram Joshi, Mobile SDK Specialist',
    syllabus: [
      'Dart Programming Language: Fundamentals, Async/Await, OOP',
      'Flutter Widgets: Stateless vs Stateful, Layouts, Material Design',
      'State Management: Provider, Bloc, and Riverpod frameworks',
      'Native Device Access: Camera, GPS, Local storage (Hive/SQLite)',
      'Firebase Integration: Authentication, Firestore, and Push Notifications',
      'Cross-Platform Compilation: Creating iOS, Android & Web Builds',
    ],
    projects: [
      'Cryptocurrency Live Tracker Application',
      'Social Networking & Event Locator Map App',
      'Offline Recipes App with Firebase Backup',
    ],
    certificationDetails: 'ISO Certified Flutter Developer Credentials. Co-verified with Mountreach Solution Private Limited Stamp.',
    image: 'flutter',
  },
  {
    title: 'Cyber Security & Ethical Hacking',
    description: 'Learn network security, web application vulnerability assessment, systems hacking, cryptography, and penetration testing methods.',
    category: 'Security',
    price: 4999,
    duration: '10 Weeks',
    level: 'Advanced',
    instructor: 'Karan Patil, Certified Ethical Hacker (CEH)',
    syllabus: [
      'Networking Protocols, TCP/IP Suite, and Linux Terminal Basics',
      'Information Gathering & Scanning: Nmap, Wireshark, Banner Grabbing',
      'Web Application Pentesting: OWASP Top 10 (SQLi, XSS, CSRF, IDOR)',
      'System Hacking: Privilege Escalation, Exploits, and Metasploit Framework',
      'Wireless Network Security & Cryptographic Algorithms',
      'Defensive Security: Firewalls, IDS/IPS, Incident Response, Log Analysis',
    ],
    projects: [
      'Vulnerability Audit Report for E-Commerce Gateway',
      'Custom Port Scanner and Intrusion Alert tool in Python',
      'Secure Encrypted Communication Chatroom Client',
    ],
    certificationDetails: 'Certified Ethical Associate Verification. ISO 9001:2015 Verified stamp for diploma and engineering grads.',
    image: 'cybersecurity',
  },
];

const internshipsData = [
  {
    title: 'Artificial Intelligence Intern',
    description: 'Work on computer vision datasets, train deep learning models, and deploy NLP models in microservices. Collaborate directly with senior AI researchers.',
    duration: '6 Months',
    stipend: '₹8,000 - ₹12,000 / Month',
    skillsRequired: ['Python', 'TensorFlow / PyTorch', 'OpenCV', 'Machine Learning Basics'],
    projects: ['Edge-AI Object Detection for Manufacturing', 'Customer Support LLM Finetuning'],
    company: 'Mountreach Solution Private Limited',
    isoCertified: true,
  },
  {
    title: 'Android App Development Intern',
    description: 'Contribute to native Android client products. Maintain Jetpack Compose interfaces, integrate REST endpoints, and fix structural bugs.',
    duration: '3-6 Months',
    stipend: '₹5,000 - ₹10,000 / Month',
    skillsRequired: ['Kotlin', 'Android SDK', 'Retrofit', 'Jetpack Compose'],
    projects: ['Mountreach Attendance Tracking Client', 'Digital Catalog Application'],
    company: 'Mountreach Solution Private Limited',
    isoCertified: true,
  },
  {
    title: 'MERN Stack Web Developer Intern',
    description: 'Help build and scale customer-facing portals. Work on React user flows, develop backend API endpoints, and optimize MongoDB pipelines.',
    duration: '6 Months',
    stipend: '₹6,000 - ₹11,000 / Month',
    skillsRequired: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'Redux/Context API'],
    projects: ['Interactive Virtual Classroom Portal', 'Student Placement Dashboard Module'],
    company: 'Mountreach Solution Private Limited',
    isoCertified: true,
  },
  {
    title: 'Cyber Security Analyst Intern',
    description: 'Conduct routine penetration testing on corporate applications, perform vulnerability audits, and monitor server logs for security anomalies.',
    duration: '3 Months',
    stipend: '₹7,000 - ₹10,000 / Month',
    skillsRequired: ['Linux CLI', 'OWASP Top 10', 'Nmap / Wireshark', 'Bash/Python Scripting'],
    projects: ['Corporate Web API Audits', 'Internal Network Security Mapping'],
    company: 'Mountreach Solution Private Limited',
    isoCertified: true,
  },
];

module.exports = { coursesData, internshipsData };
